a = input("enter your name")
print("hello"+str(a))
b = input("how are you")
c = input("what are you looking for")
d = input("what kind of engineer sir")
print("please give us a moment sir")
print("yes sir,we found matches for your requirement")
e = input("may i get there office address")
print("yes sir")
e = input("6446431364 naresh,mechanical engineer")
print("for more information you can contact us again")
